<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy for HostKrlo</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
            padding: 20px;
            background-color: #f9f9f9;
        }
        h1, h2, h3 {
            color: #333;
        }
        p {
            color: #555;
        }
        ul {
            margin-left: 20px;
        }
    </style>
</head>
<body>

    <h1>Privacy Policy for HostKrlo</h1>
    <p><strong>Last updated: October 22, 2024</strong></p>

    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p>

    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
        <li><strong>Account:</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate:</strong> means an entity that controls, is controlled by or is under common control with a party.</li>
        <li><strong>Company:</strong> refers to Hostkrlo, under CK DIGITAL ENTERPRISES, Darbhanga, Bihar, India.</li>
        <li><strong>Cookies:</strong> are small files that are placed on Your device by a website.</li>
        <li><strong>Country:</strong> refers to: Darbhnaga, Bihar, India.</li>
        <li><strong>Device:</strong> means any device that can access the Service.</li>
        <li><strong>Personal Data:</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service:</strong> refers to the Website.</li>
        <li><strong>Service Provider:</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
        <li><strong>Usage Data:</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><strong>Website:</strong> refers to CK DIGITAL ENTERPRISES, accessible from <a href="https://hostkrlo.com">https://hostkrlo.com</a>.</li>
        <li><strong>You:</strong> means the individual accessing or using the Service.</li>
    </ul>

    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.</p>
    <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
    </ul>

    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service and may include information such as Your Device's Internet Protocol address, browser type, and other diagnostic data.</p>

    <h2>Tracking Technologies and Cookies</h2>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.</p>

    <h2>Use of Your Personal Data</h2>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
        <li>To provide and maintain our Service.</li>
        <li>To manage Your Account.</li>
        <li>For the performance of a contract.</li>
        <li>To contact You.</li>
        <li>To provide You with news, special offers, and general information.</li>
        <li>To manage Your requests.</li>
    </ul>

    <h2>Retention of Your Personal Data</h2>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>

    <h2>Transfer of Your Personal Data</h2>
    <p>Your information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction.</p>

    <h2>Delete Your Personal Data</h2>
    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>

    <h2>Disclosure of Your Personal Data</h2>
    <p>If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred.</p>

    <h2>Security of Your Personal Data</h2>
    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure.</p>

    <h2>Children's Privacy</h2>
    <p>Our Service does not address anyone under the age of 13.</p>

    <h2>Links to Other Websites</h2>
    <p>Our Service may contain links to other websites that are not operated by Us.</p>

    <h2>Changes to this Privacy Policy</h2>
    <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
    <p>By email: <a href="mailto:support@hostkrlo.com">support@hostkrlo.com</a></p>

</body>
</html>
